name: Coding Standard

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/cs.yml'
    branches:
      - master
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/cs.yml'
    branches:
      - '**'

jobs:
  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          coverage: none
          pecl: false

      - name: composer install
        run: composer install

      - name: Run PHP CodeSniffer
        run: composer cs-check
