name: PHPUnit
on:
  push:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/phpunit.yml'
    branches:
      - master
  pull_request:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/phpunit.yml'
    branches:
      - '**'
jobs:
  phpunit:
    name: ${{ matrix.applications }} (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      extensions: mbstring, xml, ctype, iconv, mysql, imagick, openssl, intl
      key: cache-v20200302 # can be any string, change to clear the extension cache.
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
      - name: Display informations
        run: |
          export DATABASE_TEST_URL="mysql://root:root@localhost:${{ job.services.mysql.ports['3306'] }}/test"
          echo "port = ${{ job.services.mysql.ports['3306'] }}"
          php -v
          composer --version
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          chmod +x bin/cake
      - name: Run migration
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: |
          bin/cake migrations migrate
          bin/cake migrations status
      - name: Run PHPUnit
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: |
          vendor/bin/phpunit  --configuration ${{ matrix.applications }}.phpunit.xml --log-junit tmp/testsuites.xml
